name: tarefas
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.5
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  firebase_auth: ^4.17.8
  dio: ^5.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

