// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDj0ez8LgZfzAzVL3uCJ9qKyaBos0lf6U',
    appId: '1:85656976480:web:b9629aba783f003a78d705',
    messagingSenderId: '85656976480',
    projectId: 'tarefas-a511a',
    authDomain: 'tarefas-a511a.firebaseapp.com',
    storageBucket: 'tarefas-a511a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWrDxf_NDddz2fRAMjPvfhRab837rJmIc',
    appId: '1:85656976480:android:e209d3e3a900f4e878d705',
    messagingSenderId: '85656976480',
    projectId: 'tarefas-a511a',
    storageBucket: 'tarefas-a511a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjyd_iw2h571sz1faSF1IDWTEQeDMtgCc',
    appId: '1:85656976480:ios:87f78ac9c70ee9b578d705',
    messagingSenderId: '85656976480',
    projectId: 'tarefas-a511a',
    storageBucket: 'tarefas-a511a.appspot.com',
    iosBundleId: 'com.example.tarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjyd_iw2h571sz1faSF1IDWTEQeDMtgCc',
    appId: '1:85656976480:ios:e29565f1bf3d665678d705',
    messagingSenderId: '85656976480',
    projectId: 'tarefas-a511a',
    storageBucket: 'tarefas-a511a.appspot.com',
    iosBundleId: 'com.example.tarefas.RunnerTests',
  );
}
