// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARPU6GHaN62MRgMvNuFETnarn52noAl_A',
    appId: '1:891238539311:web:73d9b7580e51b3a719a6da',
    messagingSenderId: '891238539311',
    projectId: 'mytask-bb756',
    authDomain: 'mytask-bb756.firebaseapp.com',
    storageBucket: 'mytask-bb756.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNtKyiDxKaouR-5-Gjh4Cky8_d68gtiis',
    appId: '1:891238539311:android:c1e7e610b58405f319a6da',
    messagingSenderId: '891238539311',
    projectId: 'mytask-bb756',
    storageBucket: 'mytask-bb756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1BDxaHDQGcVf62eELstTzN2_TVrTQt-4',
    appId: '1:891238539311:ios:a5f049cd78c1454419a6da',
    messagingSenderId: '891238539311',
    projectId: 'mytask-bb756',
    storageBucket: 'mytask-bb756.appspot.com',
    iosBundleId: 'com.example.tarefas',
  );
}
